create table author (id integer generated by default as identity, birth_date date, name varchar(255), surname varchar(255), primary key (id));
create table author_book (author_id integer not null, book_id integer not null, primary key (author_id, book_id));
create table book (id integer generated by default as identity, release_date date, title varchar(255), primary key (id));
create table user_tbl (id integer generated by default as identity, email varchar(255), name varchar(255), password varchar(255), surname varchar(255), primary key (id));
create table user_book (user_id integer not null, book_id integer not null, primary key (user_id, book_id));
alter table author_book add constraint FKn8665s8lv781v4eojs8jo3jao foreign key (book_id) references book;
alter table author_book add constraint FKg7j6ud9d32ll232o9mgo90s57 foreign key (author_id) references author;
alter table user_book add constraint FK85pwltn867pjxog1gk5smtqcw foreign key (book_id) references book;
alter table user_book add constraint FKbc0bwdnndnxhct38sinbem0n0 foreign key (user_id) references user_tbl;